role: gs
GS-SAC: 17
port: 8080
debug: 1

gs:
  peer_server_port: 23457
  peers:
    - peer_addr: 127.0.0.1
      peer_port: 23456
      peer_SAC: 16

gsnf:
  gsnf_addr: 127.0.0.1
  gsnf_addr_v6: ::1
  #gsnf_remote_port: 55564
  gsnf_remote_port: 55559
  gsnf_local_port: 55565

init_fl_freq: 1112.0
init_rl_freq: 966.0
http:
  http_port: 9890
